name: polkadot_marketplace
description: "A Flutter-based decentralized marketplace powered by Polkadot blockchain."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  image_picker: ^1.0.7
  http: ^1.2.0
  polkadart: ^0.4.5
  polkadart_keyring: ^0.4.4
  shared_preferences: ^2.2.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/marketplace.json
    