cargo-features = ["panic-immediate-abort"]

[package]
name = "marketplace"
version = "1.0.0"
edition = "2021"

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = ["ink/std", "scale/std", "scale-info/std"]

[dependencies]
ink = { version = "5.1.1", default-features = false }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2", default-features = false, features = ["derive"], optional = true }
const_env = "0.1.5"

[profile.release]
panic = "immediate-abort"
